[program:jiratime]
command=/home/cca-user/jiratime/jiratime
autostart=true
autorestart=true
startretries=10
user=root
directory=/home/cca-user/jiratime/
redirect_stderr=true
stdout_logfile=/var/log/supervisor/jiratime.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
